name: Run Tournament
# Run every Sunday at Noon
on:
  schedule:
    - cron: "0 12 * * 0"
  push:
    branches:
      - workflow_testing
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2
      - name: Get Python
        uses: actions/setup-python@v1.2.0
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip3 install --upgrade pip
          pip3 install -r requirements.txt
      - name: Qualify
        env:
          TIME_LIMIT: 5
        run: python3 tournament.py $TIME_LIMIT
